//go:build ignore

// Gen writes data.go, the emoji and their names in groups, from Unicode's emoji-test.txt:
//
//	go run gen.go emoji-test.txt
//
// It keeps the fully qualified emoji, leaves out the skin tones of each and the Component group, and keeps each
// emoji's short name and the version of Emoji it arrived in.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) != 2 {
		log.Fatal("usage: go run gen.go emoji-test.txt")
	}
	f, err := os.Open(os.Args[1])
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	var b bytes.Buffer
	b.WriteString("// Code generated by gen.go from Unicode's emoji-test.txt. DO NOT EDIT.\n\n")
	b.WriteString("package emoji\n\n")
	b.WriteString("var groups = []Group{\n")
	group, version := "", ""
	open := false
	s := bufio.NewScanner(f)
	for s.Scan() {
		line := s.Text()
		switch {
		case strings.HasPrefix(line, "# Version:"):
			version = strings.TrimSpace(strings.TrimPrefix(line, "# Version:"))
		case strings.HasPrefix(line, "# group:"):
			if open {
				b.WriteString("}},\n")
			}
			group = strings.TrimSpace(strings.TrimPrefix(line, "# group:"))
			open = group != "Component"
			if open {
				fmt.Fprintf(&b, "{Name: %q, Emoji: []Emoji{\n", group)
			}
		case !open || line == "" || strings.HasPrefix(line, "#"):
		default:
			codes, rest, ok := strings.Cut(line, ";")
			if !ok || !strings.HasPrefix(strings.TrimSpace(rest), "fully-qualified") {
				continue
			}
			_, comment, _ := strings.Cut(rest, "#")
			fields := strings.Fields(comment)
			if len(fields) < 3 {
				continue
			}
			var runes []rune
			tone := false
			for _, c := range strings.Fields(codes) {
				v, err := strconv.ParseUint(c, 16, 32)
				if err != nil {
					log.Fatalf("%q: %v", line, err)
				}
				if v >= 0x1F3FB && v <= 0x1F3FF {
					tone = true
				}
				runes = append(runes, rune(v))
			}
			if tone {
				continue
			}
			since := strings.TrimPrefix(fields[1], "E")
			name := strings.Join(fields[2:], " ")
			fmt.Fprintf(&b, "{%q, %q, %q},\n", string(runes), name, since)
		}
	}
	if err := s.Err(); err != nil {
		log.Fatal(err)
	}
	if open {
		b.WriteString("}},\n")
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "// unicodeVersion is the version of Emoji the data comes from.\nconst unicodeVersion = %q\n", version)
	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("data.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
}
